# Generated by Django 4.1.5 on 2023-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todoapp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
